---
apiVersion: v1
kind: Template
metadata:
  name: slack-mcp
parameters:
  - name: IMAGE
    value: quay.io/redhat-ai-tools/slack-mcp
  - name: IMAGE_TAG
    value: latest
  - name: MCP_TRANSPORT
    value: sse
  - name: FASTMCP_HOST
    value: "0.0.0.0"
  - name: LOGS_CHANNEL_ID
    value: C0700000000
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: slack-mcp
    name: slack-mcp
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: slack-mcp
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: slack-mcp
      spec:
        containers:
        - name: slack-mcp
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
          - name: MCP_TRANSPORT
            value: ${MCP_TRANSPORT}
          - name: FASTMCP_HOST
            value: ${FASTMCP_HOST}
          - name: LOGS_CHANNEL_ID
            value: ${LOGS_CHANNEL_ID}
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: slack-mcp
    labels:
      app: slack-mcp
  spec:
    selector:
      app: slack-mcp
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: slack-mcp
    labels:
      app: slack-mcp
  spec:
    to:
      kind: Service
      name: slack-mcp
    port:
      targetPort: 8000
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
